const Login = JSON.parse(localStorage.getItem("Login"));

if (Login == null) {
  localStorage.setItem("Login", false);
}

const presentuser = JSON.parse(localStorage.getItem("presentuser"));

if (presentuser == null) {
  let data = {};
  localStorage.setItem("presentuser", JSON.stringify(data));
}

const bookdata = JSON.parse(localStorage.getItem("bookdata"));

if (bookdata == null) {
  let data = [];
  localStorage.setItem("bookdata", JSON.stringify(data));
}

const users = JSON.parse(localStorage.getItem("users"));

if (users == null) {
  let data = [];
  localStorage.setItem("users", JSON.stringify(data));
}

const buslist = JSON.parse(localStorage.getItem("buslist"));

if (buslist == null) {
  const busdatalist = [
    {
      busid: 0,
      from: `Hyderabad`,
      to: `Vijayawada`,
      busname: `ORANGE TOURS AND TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `6:00 AM`,
      droptime: `11:00 AM`,
      distance: `400 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 1,
      from: `Hyderabad`,
      to: `Vijayawada`,
      busname: `TSRTC`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `11:00 AM`,
      droptime: `05:00 PM`,
      distance: `398 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 2,
      from: `Hyderabad`,
      to: `Vijayawada`,
      busname: `OLA TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `7:00 PM`,
      droptime: `11:00 PM`,
      distance: `392 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 3,
      from: `Hyderabad`,
      to: `Vijayawada`,
      busname: `UBER TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 PM`,
      droptime: `10:00 PM`,
      distance: `542 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 4,
      from: `Hyderabad`,
      to: `chennai`,
      busname: `SAMSUNG TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `6:00 AM`,
      droptime: `11:00 AM`,
      distance: `415 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 5,
      from: `Hyderabad`,
      to: `chennai`,
      busname: `APSRTC`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `11:00 AM`,
      droptime: `05:00 PM`,
      distance: `425 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 6,
      from: `Hyderabad`,
      to: `chennai`,
      busname: `I - BUS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `7:00 PM`,
      droptime: `11:00 PM`,
      distance: `395 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 7,
      from: `Hyderabad`,
      to: `chennai`,
      busname: `KERALA BUS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 PM`,
      droptime: `10:00 PM`,
      distance: `800 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 8,
      from: `Hyderabad`,
      to: `banglore`,
      busname: `BANGLORE TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `6:00 AM`,
      droptime: `11:00 AM`,
      distance: `705 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 9,
      from: `Hyderabad`,
      to: `banglore`,
      busname: `BSRTC`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `11:00 AM`,
      droptime: `05:00 PM`,
      distance: `921 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 10,
      from: `Hyderabad`,
      to: `banglore`,
      busname: `OLA TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `7:00 PM`,
      droptime: `11:00 PM`,
      distance: `790 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 11,
      from: `Hyderabad`,
      to: `banglore`,
      busname: `INDIAN TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 PM`,
      droptime: `10:00 PM`,
      distance: `795 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 12,
      from: `Vijayawada`,
      to: `Hyderabad`,
      busname: `MAXMAX BUS TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `12:00 PM`,
      droptime: `6:00 PM`,
      distance: `665 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 13,
      from: `Vijayawada`,
      to: `Hyderabad`,
      busname: `KARODA TRAVELS`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `05:00 PM`,
      droptime: `11:00 PM`,
      distance: `856 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 14,
      from: `Vijayawada`,
      to: `Hyderabad`,
      busname: `RATNADEEP TRAVELS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `06:00 AM`,
      droptime: `11:00 AM`,
      distance: `786 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 15,
      from: `Vijayawada`,
      to: `Hyderabad`,
      busname: `COMFORT TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 AM`,
      droptime: `10:00 AM`,
      distance: `696 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 16,
      from: `Vijayawada`,
      to: `chennai`,
      busname: `RAMPAGE TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `12:00 PM`,
      droptime: `6:00 PM`,
      distance: `795 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 17,
      from: `Vijayawada`,
      to: `chennai`,
      busname: `KSRTC`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `05:00 PM`,
      droptime: `11:00 PM`,
      distance: `442 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 18,
      from: `Vijayawada`,
      to: `chennai`,
      busname: `GANGOTHRI TRAVELS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `06:00 AM`,
      droptime: `11:00 AM`,
      distance: `916 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 19,
      from: `Vijayawada`,
      to: `chennai`,
      busname: `PERFECT TRAVELS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 AM`,
      droptime: `10:00 AM`,
      distance: `596 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 20,
      from: `Vijayawada`,
      to: `banglore`,
      busname: `SANDEEP TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `12:00 PM`,
      droptime: `6:00 PM`,
      distance: `696 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 21,
      from: `Vijayawada`,
      to: `banglore`,
      busname: `NAGARJUNA TRAVELS`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `05:00 PM`,
      droptime: `11:00 PM`,
      distance: `747 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 22,
      from: `Vijayawada`,
      to: `banglore`,
      busname: `RAM TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `06:00 AM`,
      droptime: `11:00 AM`,
      distance: `669 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 23,
      from: `Vijayawada`,
      to: `banglore`,
      busname: `YERUN TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 AM`,
      droptime: `10:00 AM`,
      distance: `490 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 24,
      from: `chennai`,
      to: `Hyderabad`,
      busname: `DEEPAK TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `12:00 PM`,
      droptime: `6:00 PM`,
      distance: `665 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 25,
      from: `chennai`,
      to: `Hyderabad`,
      busname: `RAMYA TOURS`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `05:00 PM`,
      droptime: `11:00 PM`,
      distance: `715 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 26,
      from: `chennai`,
      to: `Hyderabad`,
      busname: `SHRAVANI TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `06:00 AM`,
      droptime: `11:00 AM`,
      distance: `561 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 27,
      from: `chennai`,
      to: `Hyderabad`,
      busname: `SAJJAD TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 AM`,
      droptime: `10:00 AM`,
      distance: `442 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 28,
      from: `chennai`,
      to: `banglore`,
      busname: `BHANU TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `12:00 PM`,
      droptime: `6:00 PM`,
      distance: `696 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 29,
      from: `chennai`,
      to: `banglore`,
      busname: `ARPIT TRAVELS`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `05:00 PM`,
      droptime: `11:00 PM`,
      distance: `548 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 30,
      from: `chennai`,
      to: `banglore`,
      busname: `PRASHANTH TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `06:00 AM`,
      droptime: `11:00 AM`,
      distance: `236 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 31,
      from: `chennai`,
      to: `banglore`,
      busname: `YESH TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 AM`,
      droptime: `10:00 AM`,
      distance: `295 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 32,
      from: `chennai`,
      to: `Vijayawada`,
      busname: `NISHANTH LUXURY`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `12:00 PM`,
      droptime: `6:00 PM`,
      distance: `1200 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 33,
      from: `chennai`,
      to: `Vijayawada`,
      busname: `RISHAB COMFORT TRAVELS`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `05:00 PM`,
      droptime: `11:00 PM`,
      distance: `1295 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 34,
      from: `chennai`,
      to: `Vijayawada`,
      busname: `RUGENER TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `06:00 AM`,
      droptime: `11:00 AM`,
      distance: `1156 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 35,
      from: `chennai`,
      to: `Vijayawada`,
      busname: `OLA TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 AM`,
      droptime: `10:00 AM`,
      distance: `1254 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 36,
      from: `banglore`,
      to: `chennai`,
      busname: `ORANGE TOURS AND TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `12:00 PM`,
      droptime: `6:00 PM`,
      distance: `1094 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 37,
      from: `banglore`,
      to: `chennai`,
      busname: `UBER TOURS`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `05:00 PM`,
      droptime: `11:00 PM`,
      distance: `210 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 38,
      from: `banglore`,
      to: `chennai`,
      busname: `KOLA TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `06:00 AM`,
      droptime: `11:00 AM`,
      distance: `300 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 39,
      from: `banglore`,
      to: `chennai`,
      busname: `NOKIA TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 AM`,
      droptime: `10:00 AM`,
      distance: `405 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 40,
      from: `banglore`,
      to: `Hyderabad`,
      busname: `ORANGE TOURS AND TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `12:00 PM`,
      droptime: `6:00 PM`,
      distance: `295 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 41,
      from: `banglore`,
      to: `Hyderabad`,
      busname: `SAM TRAVELS`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `05:00 PM`,
      droptime: `11:00 PM`,
      distance: `312 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 42,
      from: `banglore`,
      to: `Hyderabad`,
      busname: `REDBUS TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `06:00 AM`,
      droptime: `11:00 AM`,
      distance: `295 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 43,
      from: `banglore`,
      to: `Hyderabad`,
      busname: `ABHIBUS TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 AM`,
      droptime: `10:00 AM`,
      distance: `216 kms`,
      seats: 25,
      price: 1200,
    },
    {
      busid: 44,
      from: `banglore`,
      to: `Vijayawada`,
      busname: `RAPIDO TOURS AND TRAVELS`,
      bustype: `NON-AC Seater/Sleeper (2 + 1)`,
      starttime: `12:00 PM`,
      droptime: `6:00 PM`,
      distance: `216 kms`,
      seats: 35,
      price: 550,
    },
    {
      busid: 45,
      from: `banglore`,
      to: `Vijayawada`,
      busname: `SWIGGY TOURS`,
      bustype: `RAJDHANI (A.C. Semi Sleeper) - 1177`,
      starttime: `05:00 PM`,
      droptime: `11:00 PM`,
      distance: `442 kms`,
      seats: 28,
      price: 850,
    },
    {
      busid: 46,
      from: `banglore`,
      to: `Vijayawada`,
      busname: `ZOMATO TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `06:00 AM`,
      droptime: `11:00 AM`,
      distance: `662 kms`,
      seats: 25,
      price: 1250,
    },
    {
      busid: 47,
      from: `banglore`,
      to: `Vijayawada`,
      busname: `UBER TOURS`,
      bustype: `AC-SLEEPER - LUXURY`,
      starttime: `6:00 AM`,
      droptime: `10:00 AM`,
      distance: `225 kms`,
      seats: 25,
      price: 1200,
    },
  ];

  localStorage.setItem(`buslist`, JSON.stringify(busdatalist));
}
